# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure', models.IntegerField()),
                ('income', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expenditure', models.IntegerField()),
                ('total_income', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='daily_info',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='useraccount.UserAccount'),
        ),
    ]
