# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('total_expenditure', models.IntegerField()),
                ('total_income', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AlterField(
            model_name='daily_info',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='useraccount.Month'),
        ),
    ]
