# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_auto_20180528_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_info',
            name='added_at',
        ),
        migrations.AddField(
            model_name='daily_info',
            name='date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily_info',
            name='expenditure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily_info',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='total_expenditure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='total_income',
            field=models.IntegerField(default=0),
        ),
    ]
