# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20180528_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_info',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='useraccount.Month'),
        ),
    ]
